### ISSUE TITLE
Воу воу воу

### ISSUE THREAD

**Issue by archanger** [kuznet-sova/NationalGeographicApp#13]
https://github.com/kuznet-sova/NationalGeographicApp/blob/ed71f49d8d0b4821fb84a5b5e9cf24124ab767de/NationalGeographicApp/ViewControllers/StoriesTableViewController.swift#L52-L62

За такое публично осмеивают 🤣 

да, тут логика так-то простецкая, но читается это ужасно) весь кусок надо вынести в отдельную функцию и через `guard` красиво возвращать `url`ы

**Comment by kuznet-sova** [comment]
Вынесла отдельно, urlы вытащила в переменные, логику никак не могу от if/else на guard перетащить 😞

**Comment by kirill-chuyanov** [comment]
```swift
if let url = storie.leadMedia?.image?.uri { 
    return url
 } 

if let url = storie.leadMedia?.video?.image?.uri { 
    return url
 } 
/// и так далее... да, guard тут не особо годится 😞 
```

**Comment by kuznet-sova** [comment]
Поняла, построчно лучше разбить, ок
