### ISSUE TITLE
Нет

### ISSUE THREAD

**Issue by archanger** [kuznet-sova/NationalGeographicApp#16]
https://github.com/kuznet-sova/NationalGeographicApp/blob/ed71f49d8d0b4821fb84a5b5e9cf24124ab767de/NationalGeographicApp/ViewControllers/StartViewController.swift#L21

воу воу воу 😅  NetworkManager вообще не должен ничего знать про UI

есть такая штука SOLID, это 5 важных принципов, если их придерживаться, то больше ничего знать и не надо, чтобы писать хороший, поддерживаемый код 😉

**Comment by kuznet-sova** [comment]
done
