### ISSUE TITLE
тоже нет

### ISSUE THREAD

**Issue by archanger** [kuznet-sova/NationalGeographicApp#17]
https://github.com/kuznet-sova/NationalGeographicApp/blob/ed71f49d8d0b4821fb84a5b5e9cf24124ab767de/NationalGeographicApp/ViewControllers/StartViewController.swift#L29-L45

Старайся избегать колбэка в колбэке, это называется callback hell и выглядит он вот так 

![1*zxx4iQAG4HilOIQqDKpxJw](https://user-images.githubusercontent.com/10977678/101548601-cf50af00-39b4-11eb-935c-242dcf6076d7.jpeg)

**Comment by kuznet-sova** [comment]
done
