### ISSUE TITLE
Give Some Respect to English

### ISSUE THREAD

**Issue by archanger** [kuznet-sova/NationalGeographicApp#18]
https://github.com/kuznet-sova/NationalGeographicApp/blob/ed71f49d8d0b4821fb84a5b5e9cf24124ab767de/NationalGeographicApp/ViewControllers/FilteringPickerViewController.swift#L43

ваще не уважаешь) `catigorie` 😸

**Comment by kuznet-sova** [comment]
Нашел таки, поправила)
